spring.application.name=ClassProjectLibraryManagementSoftware
server.port=1000
server.servlet.context-path=/librarySoftware

##Data Source Configs
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=DAka@24381
#spring.datasource.url=jdbc:mysql://localhost:3306/LibraryManagemetSystem?createDatabaseIfNotExist=true


spring.datasource.url=jdbc:mysql://localhost:3306/LibraryManagemetSystem?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=DAka@24381
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true # Formats SQL queries for better readability

# Util
perDayFine = 5.00

##Security
signature=8bd527fab517956fbfb224512abb05f1e41eeb8ae1e86936f6b82047d3c1e2b2ceb0206825bf6ad90e534364b7f1ae74f8fd5bce549f802521baceb494b54e2be4f681cddf7f55ab91f3c174c9f36ae83c10d80f73e404b729a72e0a7b9d99e2d02422f98f92bc9e0f3b9496391c985c7535a90fa5f398c104b340d52865052663a42eb8105b3c7821b14a6d098a3a2eb18d4c8a992a33bc74d30e9190557705e876956g43983d291eca82ef6467b3c1aca69e002e6bbea95fa9f4d4a161af032636d3e82f3351a0caa9178c678afbe175440f03b06951482b0829cd7555rg069ac85d724bb7fe1231da0bc5tcb6e809263ecb880a7dc7ffd7726687322aa2925

